- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print course informatiom
    ansible.builtin.debug:
     msg: "Hello i am Learning {{ COURSE }} , Duration: {{ DURATION }} , tainer is : {{ TRAINER }} "