- name: functions
  hosts: local
  connection: local
  vars:
   persons: "Ramesh,suresh,Raheem,joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
     msg: "Hello, {{ person  | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello  {{ persons | split(',') }}"
  
  - name: convert map in into List
    vars:
     course:
      name: ansible
      duration: 10hr
      trainer: sivakumar
    ansible.builtin.debug:
     msg: "Course info: {{ course | dict2items }} "
  
  - name: convert List into map
    vars:
     course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict  }}"

  - name: convert to uppercase
    vars:
      name: "SivaKumar Reddy M"
    ansible.builtin.debug:
       msg: "Hello {{ name | upper}}"
  
  - name: convert to uppercase
    vars:
      name: "SHIVAKUMAR REDDY M"
    ansible.builtin.debug:
       msg: "Hello {{ name | lower}}"
