- name: functions
  hosts: local
  connection: local
  vars:
   persons: "Ramesh,suresh,Raheem,joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
     msg: "Hello, {{ person  | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello  {{ persons | split(',') }}"
  
  - name: convert map in into List
    vars:
     course:
      name: ansible
      duration: 10hr
      trainer: sivakumar
    ansible.builtin.debug:
     msg: "Course info: {{ course | dict2items }} "
