- name: user creation
  hosts: local
  connection: local
  tasks:
  - name: check roboshop user exis or not
    ansible.builtin,command: id roboshop
    register: output
    ignore_errors: true

  - name: create user
    become: yes
    ansible.builtin.command: useradd roboshop
    when: output.rc != 0
  
  - name: user alredy exits
    ansible.builtin.debug:
      msg: "useradd roboshop exits"
    when: output.rc == 0
